
version: '3'

services:
  postgres_database:
    image: postgres
    restart: always
    volumes:
      -  postgres_database:/var/lib/postgresql/data
    env_file:
      - nc_db.env

  nextcloud_app:
    image: nextcloud:apache
    restart: always
    volumes:
      - nextcloud:/var/www/html
    env_file:
      - nc_db.env
    depends_on:
      - postgres_database
    networks:
      - proxy-tier
      - default

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

  collabora-code:
    image: collabora/code
    expose:
      - 9980
    env_file:
      - collabora.env
    ports:
      - "9980"
    restart: always
    cap_add:
      - ALL
    networks:
      - proxy-tier

volumes:
  postgres_database:
  nextcloud:
  certs:
  vhost.d:
  html:

networks:
  proxy-tier:
  default:
